### PR TITLE
Switch to ES6 modules

### PR DESCRIPTION
**Pull request by FND**
As proposed in #69.

From the commit messages:

> this effectively constitutes a rewrite, based on and guided by the
> previous implementation, with the following goals:
> * lightweight and efficient
> * engine-agnostic, i.e. supporting browsers as well as Node/Nashorn/…
> * modular: since ASCII is considered the default, we don't want to
>   impose size or performance penalties for the sake of custom charsets
> * modern: ES6 (or ES2015, to be precise) provides standardized
>   modularity as well as a bit of syntactic sugar - plus there's value in
>   going along with the community, now that ES6 is generally accepted
>
> notes and caveats:
> * `legacy.js` continues to provide the v1.x API for backwards
>   compatibility (the term "legacy" is not intended to be derogatory in
>   any way)
> * since the source code is now ES6 modules, users are expected to either
>   support ES2015 natively or transpile to ES5
>   originally I'd hoped for `legacy.js` to remain a CommonJS module, but
>   then we wouldn't be able to import our new implementation
> * consequently, using esm <https://github.com/standard-things/esm> in
>   tests and benchmark to make Node accept `import`/`export` syntax
>   (while from Node v8.5.0, this is supported natively, that only applies
>   to `.mjs` files)
> * benchmarks - both the existing Node harness and an ad-hoc setup in the
>   browser - suggest this implementation is faster than the previous one,
>   though it would be nice for that to be confirmed independently
> * while `encode` is almost identical in both versions (ASCII-optimized
>   vs. custom charsets), I opted not to worry excessively about DRYness
>   for the sake of runtime efficiency
> * not sure about code style (e.g. quotation marks, keyword spacing etc.)

The second commit should be considered optional:

> added ES5 distribution
>
> I'm not convinced this is a great idea:
> * while faucet-pipeline <http://faucet-pipeline.org> makes bundling and
>   transpiling easy, it inevitably means we get Rollup and Babel as
>   fairly heavyweight dependencies (even though they're only needed for
>   development)
> * I very much dislike adding build artifacts (i.e. `base62.js`) to the
>   source repository - the alternative would be to only add it to the
>   npm package, but that would require a release script and process
>
> it might be better to leave bundling/transpiling to users - if that's
> even necessary anymore, as ES6 support is becoming increasingly
> widespread (plus there's always the v1.x line to fall back on,
> particularly because functionality-wise there's no difference)

I appreciate the [Code Climate report](https://codeclimate.com/github/andrew/base62.js/pull/70), but will hold off on making modifications until we've agreed on how to proceed. (Some of the duplication is intentional; see above.) Ditto for docs.

### CODE REVIEW

**Comment by FND** [comment]
Having thought about this some more, I could easily rewrite the modules to not use ES6 features (`let`, `**`, destructuring) other than module syntax (`import`/`export`) - thus creating an ES5 CommonJS module would only require a bundler (Rollup) instead of a full-on transpiler (Babel). Of course it still leaves the question of how to handle the build artifact.

Would you prefer that, @andrew?

**Comment by andrew** [comment]
@FND yeah that sounds good, we can probably use https://github.com/semantic-release/semantic-release to automate the bundling and pushing to npm, not that it should need updating that often.

Would be good to work out a way to continue testing against old versions of node as well

**Comment by FND** [comment]
Roger:

* 325c25bae94582217809afccfc0ab26abb1c58a7 reverts back to ES5 syntax, limiting ES6 to module syntax (which pretty much gives us all the benefits we set out for)
* e1bd817b11634024c32ef20a0b2c06116326f985 gets rid of faucet, thus significantly reducing the dependency burden
* 6907f1feacb138af8f719eb4928ff1df78e97407 makes legacy tests run against the generated `base62.js` bundle

On that last point, since Base62 encoding/decoding should be fairly stable (i.e. we both don't expect frequent changes), I suppose leaving that build artifact in the repo is the most pragmatic solution.

The only caveat is that tests currently fail on Node v5 and below. However, Node v6.14.1 is currently the oldest LTS version, so I think retiring Node v5 support is reasonable?

**Comment by andrew** [comment]
Yeah, given that we'll bump to 2.0.0, dropping node 5 and down seems reasonable 👍 

Is there any extra documentation that needs to be added to the readme, perhaps around development and testing?

I'll give you write access to this repo 💯

**Comment by FND** [comment]
Thanks, much appreciate it!

Yeah, I'll add docs soon - will let you know then so you can release v2.0.0.

**Comment by FND** [comment]
So, @andrew, turns out we're not quite ready for ES6 modules yet - from tonight's commit message:

> Revert back to CommonJS modules
>
> in documenting the new API, it became apparent that distinguishing
> between entry points for legacy vs. ES6 modules is too awkward, in terms
> of both explanation and implementation
>
> plus this means we no longer need a build process and all that goes
> along with it
>
> while this might seem like a significant departure from what we set out
> to do with ES6 modules, for users the main benefit remains: since the
> code base is now split into separate modules, users only need to import
> what they need (tools for bundling modules typically understand CommonJS
> as well as ES6 modules) - though the legacy API remains the default for
> backwards compatibility

It would have been nice to run with ES6 all the way, but you're right to promote backwards compatibility. In practice, this doesn't actually make a tangible difference - particularly because tools like Rollup and webpack don't really care whether the source is CommonJS or ES6 modules.

Anyway, I've now [revised the documentation](https://github.com/FND/base62.js/blob/es6/Readme.md), so once you're happy with all that, I think we're ready to release v2.0.0.

**Comment by andrew** [comment]
👏 great work! What's your npm username? I'll add you as an owner over there as well

**Comment by FND** [comment]
Thank you! My npm username is [fnd](https://www.npmjs.com/~fnd).

If anything else comes up, I'll keep using PRs instead of pushing directly to master - just to have a second pair of eyes. (Hopefully future PRs won't require quite as much effort; I appreciate you taking the time here.)

**Comment by andrew** [comment]
@FND sounds like a great approach 👍 

Just added you as a collaborator on npm

**Comment by FND** [comment]
Excellent. Should I release v2.0.0 then?

**Comment by FND** [comment]
Done:
c0b246a928b82e2b0f1b9d6330aa855e752b4fb6
https://www.npmjs.com/package/base62

**Pull request merged**
