### PR TITLE
Fix Readme.md typo with usage examples

### PR DESCRIPTION
**Pull request by andyfusniak**
Minor typo fix for your consideration.

### CODE REVIEW

**Comment by andrew** [comment]
Thanks!

**Comment by FND** [comment]
Thanks @andyfusniak!

FWIW, when switching to modules in #70, I figured all-lowercase `base62` was more idiomatic, assuming that the initial capital was a remnant of distinguishing global variables - thus:
https://github.com/andrew/base62.js/blob/ecaf92e6e8bb1dbbaa2c4557c5d238152813e753/test/test_ascii.js#L4
vs.
https://github.com/andrew/base62.js/blob/ecaf92e6e8bb1dbbaa2c4557c5d238152813e753/test/test_legacy.js#L3
(Obviously I'd overlooked those bits in the README; good catch!)

So the README is now somewhat at odds with the internals - not that that's a big deal because it's up to the consumer anyway.

**Comment by andrew** [comment]
@andyfusniak would you be up for replacing all the `Base62` variables with `base62` in the readme?

**Comment by FND** [comment]
I went ahead and took care of that: d0be4726daea7b7e82bc0875ef837030bbc47160 - after all, it was my fault, so I figured I'd spare @andyfusniak the bureaucracy.

Thanks again!

**Pull request closed without merging**
